module.exports = [
    'tonto',
    'idiota',
    'estupido',
    'imbecil',
    'mierda',
    'cabron',
    'cabrón',
    'gilipollas',
    'puta',
    'tus muertos',
    'puto',
    'que feo eres cabron',
    'que feo eres cabrón',
    'joder',
    'coño',
    'capullo',
    'subnormal',
    'anormal',
    'mariconazo',
    'tontopolla',
    'bastardo',
    'hijoputa',
    'asqueroso',
    'tu puta madre',
    'perra',
    'perro',
    'maricon',
    'zorra',
    'eres un mal profesor',
    'explicas muy mal',
    'no me gusta',
    'no me gustas como profesor dando clases',
    'da muy mal las clases',
    'panchito',
    'pancho'
];