module.exports = [
    'tonto',
    'idiota',
    'estupido',
    'imbecil',
    'mierda',
    'cabron',
    'cabrón',
    'gilipollas',
    'puta',
    'tus muertos',
    'tus muertos a caballo',
    'tus putos muertos',
    'tu madre en tanga',
    'me cago en tus muertos',
    'me cago en tos tus muertos',
    'puto',
    'hijo de la gran puta',
    'hijo de puta',
    'hijo de las tres mil putas malparido',
    'lechoso',
    'escoria',
    'das mucho lache',
    'das mucho asco',
    'das muchisimo asco',
    'das muchisimo lache',
    'das muchisimo asco como profesor',
    'apestas',
    'apestas a gonorrea',
    'eres un mierdas',
    'que feo eres cabron',
    'que feo eres cabrón',
    'joder',
    'coño',
    'capullo',
    'subnormal',
    'anormal',
    'pedazo de maricon',
    'pedazo de maricón',
    'escoria humana',
    'mariconazo',
    'tontopolla',
    'bastardo',
    'hijoputa',
    'asqueroso',
    'tu puta madre',
    'perra',
    'perro',
    'puto perro',
    'maricon',
    'zorra',
    'eres un mal profesor',
    'explicas muy mal',
    'no me gusta',
    'no me gustas como profesor dando clases',
    'da muy mal las clases',
    'panchito',
    'panchito de mierda',
    'pancho de mierda',
    'pancho'
];